<?php
/**
 * This file is part of web-design-set with Laminas MVC framework
 * 
 * Template: 'user/partial/list-entry-users'
 * 
 * @var Laminas\View\Renderer\PhpRenderer $this
 * 
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/web-design-set
 * @license    https://opensource.org/licenses/BSD-3-Clause The BSD-3-Clause License
 * @version    1.0.0
 * @since      1.0.0
 */
?>
<?php foreach ($this->entries as $user): ?>
<section>
    <h2>
        Konto-<?= $user->getId() . "\n" ?>
    </h2>
    <ul>
        <li>
            <?= $this->escapeHtml($user->getAlias()) . "\n" ?>
        </li>
        <li>
            <?= $this->escapeHtml($user->getEmail()) . "\n" ?>
        </li>
        <li>
        <?php
            if (0 === $user->getStatus()) {
        ?>
            gesperrt
        <?php
            } else {
        ?>
            aktiv
        <?php
            }
        ?>
        </li>
    </ul>
    <div>      
        <a class="link-button-primary"  href="<?= $this->url('user-detail', ['id' => $user->getId()]); ?>">
            Anzeigen
        </a>
    </div>
</section>
<hr>
<?php endforeach ?>
