<?php

/**
 * This file is part of base application with Laminas MVC framework
 * 
 * This file is a view partial script for the main navigationbar.
 * Use this partial with Laminas\View\Helper\Navigation\Menu.
 * 
 * @package    Application
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @copyright  Copyright (c) Niklaus Höpfner
 * @link       https://github.com/nik-web/base-application
 * @license    https://opensource.org/licenses/BSD-3-Clause The BSD-3-Clause License
 * @version    1.0.0
 * @since      1.0.0
 */
?>
<button type = "button" id="hamburg-main-nav" class="hamburg">
    <span class="hamburg-line"></span>
    <span class="hamburg-line"></span>
    <span class="hamburg-line"></span>
</button>
<ul id="main-nav-bar">
<?php
    foreach ($container as $page) {
        if (!$this->navigation('main_nav')->accept($page)) {
            continue;  
        }
?>            
    <li class="main-nav-item">
<?php 
        if (!$page->hasPages()) {       
            if ($page->isActive()) {
?>
    
        <strong class="main-nav-strong">
            <?=  $page ?>
        </strong>
<?php
            } else {
?>
        <a class="main-nav-link" href="<?= $page->getHref() ?>">
            <?=  $page ?>
        </a>
<?php
            }
    
        } else {
            $classValueButton = 'main-nav-button';
            foreach ($page->getPages() as $child) {
                if (!$this->navigation()->accept($child)) {
                    continue;
                }
                if ($child->isActive()) {
                    $classValueButton = 'main-nav-button main-nav-button-active';
                }
            }
?>
        <button id="<?= $page->getId(); ?>" class="<?= $classValueButton; ?>">
            <?= $page ?>
        </button>
        <ul id="<?= $page->getId() . '-menu' ?>" class="main-nav-bar-dropdown">
        <?php
            foreach ($page->getPages() as $child) {
                if (!$this->navigation()->accept($child)) {
                    continue;
                }
        ?>
            <li class="main-nav-dropdown-item">
            <?php
                if ($child->isActive()) {
            ?>
                <strong class="main-nav-dropdown-strong">
                    <?= $child ?>
                </strong>
            <?php
                } else {
            ?>
                <a class="main-nav-dropdown-link" href="<?= $child->getHref() ?>">
                    <?= $child ?>
                </a>
            <?php
                }
            ?>                
            </li>
        <?php
            }
        ?>
        </ul>
    <?php
        }
    ?>
    </li>
<?php
    }
?>
</ul>
