<?php

/**
 * This file is part of web-design-set with Laminas MVC framework
 * 
 * This is the privacy-policy (application/privacy-policy/index) template of this web application
 * 
 * @package    Application
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @copyright  Copyright (c) Niklaus Höpfner
 * @link       https://github.com/nik-web/web-design-set
 * @license    https://opensource.org/licenses/BSD-3-Clause The BSD-3-Clause License
 * @version    1.0.0
 * @since      1.0.0
 */

$this->headTitle('Das ist die Datenschutzerklärung dieser Webanwendung');
$description = 'Das ist die Meta-Beschreibung für die Datenschutzerklärung dieser Webanwendung';
$keywords = 'Webanwendung, Datenschutz, Datenschutzerklärung';
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);
?>
<header id="main-header">
    <h1>
        Datenschutzerkl&auml;rung
    </h1>
</header>